emote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: InFlame Journal of History and Economics
description: Inflame is a student-run journal that publishes student-written history papers at the University of Chicago Laboratory Schools.
